[package]
name = "i3langlayout"
version = "0.1.0"
authors = ["Mikhail Kharitonovich <kharitonovich.m@gmail.com>"]

[dependencies]
systray = "0.2.0"
linux_raw_input_rs = "0.1.5"
png = "0.7.0"
cairo = "0.0.4"
serde_derive = "1.0.8"
serde = "1.0.8"
config = "0.6.0"
i3ipc = "0.4.2"